// for loop...........................................................................
// for (let i=0; i<10; i++) {
//     if(i===5 || i===6){
//         continue;
//     }
//     console.log(i);
// }

// while loop................................................................
// let i = 0;
// while (i < 10) { 
//   i++;
//   if (i === 4) {
//     continue;
//   }
//   console.log(i);
// }

// do while loop...........................................................
// let i=0;
// do{
// console.log(i);
// if(i===5){
//     break;
// }
// i++;
// } while(i<10);
// console.log('You breaked the loop at i = 5')

// Iterating an array.............................................................
// let arr = [24,56,85,14,62];

// arr.forEach(function(element){
//     console.log(element);
// }); 
// OR
// arr.forEach(element => {
//     console.log(element)
// });


// iterating the objects..........................................................
// const obj1 = {
//     name1 : 'SkillF',
//     age : 55,
//     role : 'Dangerous Programmer'
// }

// for (let key in obj1){
//     console.log(`The ${key} of the object is ${obj1[key]}`)
// }